version: '3'
services:
  maven-3-openjdk-17:
    build:
      context: ./java
      args:
        MAVEN_IMAGE_VERSION: 3-openjdk-17
    image: ${CI_REGISTRY_IMAGE}/maven:3-openjdk-17
  openjdk-17-onbuild:
    build:
      context: ./java/onbuild
      args:
        OPENJDK_IMAGE_VERSION: 17-jdk-oraclelinux8
    image: ${CI_REGISTRY_IMAGE}/openjdk:17-jdk-onbuild


